"""add

Revision ID: f455fbadfbb8
Revises: d92670444357
Create Date: 2024-10-06 12:05:27.576676

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f455fbadfbb8"
down_revision: Union[str, None] = "d92670444357"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "is_active",
        existing_type=sa.VARCHAR(),
        type_=sa.Boolean(),
        existing_nullable=False,
        schema="auth",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "is_active",
        existing_type=sa.Boolean(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
        schema="auth",
    )
    # ### end Alembic commands ###
